Register: Register purchase
AdminWishes: Administer wish list
AdminWishUrls: URLs for wish list pages
AdminWishList: Wish list
AdminWishUrlForAdmins: URL to admin page
AdminWishUrlForGuests: URL to guest page
RegisterNewWish: Add new wish
RegisterNewWishSubmit: Add
RegisterExplanationHeader: Explanation
RegisterExplanation: The column 'Remaining' display how many of an item that is wished but still not bought. To register a purchase: enter the number of items you've bought and click 'Register'. The page will be reloaded and the remaining number of items will be updated. When remaining is 0, it means that the 'quota' is filled for that item.
RegisterTip: Tip: If you by any chance should be unlucky and register the wrong amount of items, you can correct it by entering a negative number and press register.
HeaderWishPhoto: Photo
HeaderWishStores: Stores
HeaderWishRemaining: Remaining
HeaderWishRegister: Register
HeaderWishName: What
HeaderWishAmount: Amount
SubmitWishUpdate: Update
SubmitWishDelete: Delete
OwnerWishes: Your wish lists
ViewWishes: Wish lists shared with you
AddWishList: Create new wish list
RegisterHeader: Create new wish list
HomeHeader: Wishsys
HomeWelcome: Welcome to wishsys, a service for people wanting to share their wishes with others!
LoginGuest: Log in
HomeRegisterPreInstructions: Click
HomeRegisterLink: here
HomeRegisterPostInstructions: to register a new wish list.
HomeTitle: Wishsys
RegisterTitle: Register new wish list
WishListTitle: Wish list
LoginFormListName: Name of wish list
LoginFormPassword: Password
WishListNotFound: No such wish list
ErrorDuringLogin: An error occured while logging in
ErrorLegacyLoginName: Invalid user name
LegacyLoginPageInfo: Christian og Maries wish list. Log in with the user name and password given in the invite
InvalidUserOrPassword: Unknown wish list or wrong password
WishListCreateSuccess: Your wish list has been created
WishListCreateError: An error occured when creating wish list
RegisterFormListName: Name of wish list
RegisterFormShortNameUrl: <short name>
RegisterFormShortName: Short name used for guest URL (http://wishsys.lulf.no/wishlist/<short name>/guest)
RegisterFormAdminPassword: Administrator password
RegisterFormGuestPassword: Guest password
RegisterFormSubmit: Register
LoginFormAccessLevel: User
WishListAlreadyExists: Wish list already exists, please choose a different name
WishRegisterFormName: Name of wish
WishRegisterFormImage: Photo URL
WishRegisterFormStores: Name of stores
WishRegisterFormAmount: Amount
RegisterOwnerEmptyList: You have not added any wishes yet
RegisterWishWishAdded: Your wish was added
RegisterWishErrorAdding: An error occured while creating your wish
RegisterWishWishUpdated: Wish updated 
RegisterWishErrorChangingWish: An error occured during change/deletion of wish
RegisterWishWishDeleted: Wish deleted
GuestWishUpdate: Update
RegisterPurchasedError: An error occured when registering purchase
WishImageAlt: Photo of wish
WishListLoginHeader: Login for
WishListLoginRequired: Please login with your password below
WishListLoginFormSubmit: Log in
HomeCreateList: Create new wish list
LoggedInAs: Logged in as
LogOut: Log out
