Register: Registrere kjøp
AdminWishes: Administrer ønskeliste
AdminWishUrls: URLer til ønskeliste
AdminWishList: Ønskeliste
AdminWishUrlForAdmins: URL til administrasjonsside
AdminWishUrlForGuests: URL til gjesteside
RegisterNewWish: Legg til nytt ønske
RegisterNewWishSubmit: Legg til
RegisterExplanationHeader: Forklaring
RegisterExplanation: I kolonnen 'Gjenværende' vises det hvor mange av en gjenstand vi ønsker oss som fortsatt ikke har blitt kjøpt. For å registrere et kjøp: fyll inn hvor mange du har kjøpt av en gjenstand og trykk 'Registrer'.  Siden blir da lastet på nytt og antall gjenværende blir oppdatert. Når gjenværende er 0, betyr det at vi i utgangspunktet ikke ønsker oss flere av denne gjenstanden.
RegisterTip: Et lite tips: Om du skulle være uheldig å fylle inn eller trykke feil (f.eks. at du registrerte 3 i stedet for 2), så kan du registrere en gang til med negativt tall (skriv inn -1, og trykk 'Registrer') for å rette opp feilen.
HeaderWishPhoto: Bilde
HeaderWishStores: Butikker
HeaderWishRemaining: Gjenværende
HeaderWishRegister: Registrer
HeaderWishName: Hva
HeaderWishAmount: Antall
SubmitWishUpdate: Oppdater
SubmitWishDelete: Slett
OwnerWishes: Dine ønskelister
ViewWishes: Ønskelister delt med deg
AddWishList: Lag ny ønskeliste
RegisterHeader: Lage ny ønskeliste
HomeHeader: Ønskesys
HomeWelcome: Velkommen til ønskesys, en tjeneste for deg som vil dele dine ønsker med andre!
LoginGuest: Logg inn
HomeRegisterPreInstructions: Klikk
HomeRegisterLink: her
HomeRegisterPostInstructions: for å registrere en ny ønskeliste.
HomeTitle: Ønskesys
RegisterTitle: Registrer ny ønskeliste
WishListTitle: Ønskeliste
LoginFormListName: Navn på ønskeliste
LoginFormPassword: Passord
WishListNotFound: Fant ikke ønskeliste
ErrorDuringLogin: En feil oppstod under innlogging
ErrorLegacyLoginName: Ugylding brukernavn
LegacyLoginPageInfo: Christian og Maries ønskeliste. Logg inn med brukernavn og passord som ble gitt i invitasjonen.
InvalidUserOrPassword: Ugyldig ønskeliste/passord
WishListCreateSuccess: Ønskeliste har blitt opprettet
WishListCreateError: En feil oppstod under oppretting av ønskelisten
WishListAlreadyExists: Ønskelisten finnes allerede, vennligst velg et annet navn
RegisterFormListName: Navn på ønskeliste
RegisterFormShortNameUrl: <kortnavn>
RegisterFormShortName: Kort navn brukt i gjestelenke (http://wishsys.dimling.net/wishlist/<kortnavn>/guest)
RegisterFormAdminPassword: Passord for administrator
RegisterFormGuestPassword: Passord for gjest
RegisterFormSubmit: Registrér
LoginFormAccessLevel: Bruker
WishRegisterFormName: Navn på ønske
WishRegisterFormImage: URL til bilde
WishRegisterFormStores: Navn på butikker
WishRegisterFormAmount: Antall
RegisterOwnerEmptyList: Du har ikke lagt til noen ønsker ennå
RegisterWishWishAdded: Ønsket ble lagt til
RegisterWishErrorAdding: En feil oppstod ved opprettelse av ønske
RegisterWishWishUpdated: Ønsket ble oppdatert
RegisterWishErrorChangingWish: En feil oppstod under forandring/sletting av ønske
RegisterWishWishDeleted: Ønsket ble slettet
GuestWishUpdate: Utfør
RegisterPurchasedError: En feil skjedde under registrering av kjøp
WishImageAlt: Bilde av ønske
WishListLoginHeader: Innlogging for
WishListLoginRequired: Vennligst logg inn med passord nedenfor
WishListLoginFormSubmit: Logg inn
HomeCreateList: Lag ny ønskeliste
