Default: &defaults
  user: wishsys
  password: wishsys
  host: 192.168.1.2
  port: 5432
  database: wishsys
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: wishsys_test
  <<: *defaults

Staging:
  database: wishsys_staging
  poolsize: 100
  <<: *defaults

Production:
  database: wishsys_production
  poolsize: 100
  <<: *defaults
