Default: &defaults
  database: wishsys.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: wishsys_test.sqlite3
  <<: *defaults

Staging:
  database: wishsys_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: wishsys_production.sqlite3
  poolsize: 100
  <<: *defaults
